spring.application.name=geo-common

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.auto-offset-reset=earliest
spring.kafka.consumer.group-id=geo-common-group

spring.kafka.default-topic=base-station