spring.application.name=geo-processor

spring.datasource.username=geoMain
spring.datasource.password=geogeo
spring.datasource.url=jdbc:postgresql://localhost:5432/geo

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.kafka.consumer.group-id=geo-processor-group
spring.kafka.consumer.trigger-group-id=geo-processor-trigger-group


spring.kafka.consumer.topic-in=enrichment-stations

spring.kafka.consumer.topic-out=trigger-topic
spring.kafka.consumer.topic.partitions=5
spring.kafka.consumer.topic.replicas=1

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.auto-offset-reset=earliest
spring.kafka.default-topic=base-station

geo.processor.clickHouse.url=jdbc:clickhouse://localhost:8123/default
geo.processor.clickHouse.username=default
geo.processor.clickHouse.password=geogeo

logging.level.ru.java.maryan=DEBUG
logging.level.org.apache.kafka=WARN
logging.level.org.springframework=INFO