spring.application.name=geo-ingest

spring.kafka.consumer.group-id=filter-geo-data

spring.kafka.consumer.topic.partitions=5
spring.kafka.consumer.topic.replicas=1

spring.kafka.consumer.topic-in=from-stations
spring.kafka.consumer.topic-out=filter-stations

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.auto-offset-reset=earliest
spring.kafka.default-topic=base-station

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{traceId}] [%thread] %logger{36} - %msg%n

logging.level.ru.java.maryan=DEBUG
logging.level.org.apache.kafka=WARN
logging.level.org.springframework=INFO