spring.application.name=geo-api
management.endpoints.web.exposure.include=prometheus,health
management.metrics.tags.application=${spring.application.name}

spring.graphql.graphiql.enabled=true

geo.api.clickHouse.url=jdbc:clickhouse://clickhouse:8123/default
geo.api.clickHouse.username=default
geo.api.clickHouse.password=geogeo

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{traceId}] [%thread] %logger{36} - %msg%n

logging.level.ru.java.maryan=DEBUG
logging.level.org.apache.kafka=WARN
logging.level.org.springframework=INFO